answers/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
urlpatterns = [
    url(r'^edit/(?P<pk>\d+)/$', views.AnswerEdit.as_view(), name='edit'),
]

application/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls', namespace='core')),
]

core/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout
from . import views

urlpatterns = [
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, name='logout'),

    url(r'^questions/', include('questions.urls', namespace='questions')),
    url(r'^answers/', include('answers.urls', namespace='answers')),
    url(r'^ratingchange/', views.update_rating, name='ratingchange'),
    url(r'^$', views.index, name='index'),
]

questions/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [
    url(r'^all/$', views.QuestionsList.as_view(), name='all'),
    url(r'^new/$', views.QuestionCreate.as_view(), name='create'),
    url(r'^edit/(?P<pk>\d+)/$', views.QuestionEdit.as_view(), name='edit'),
    url(r'^question/(?P<pk>\d+)/$', views.QuestionDetail.as_view(), name='question'),
    url(r'^answers/(?P<pk>\d+)/$', views.QuestionAnswers.as_view(), name='answers'),
]

answers/models.py
# coding=utf-8

from django.db import models
import questions
from django.conf import settings
from django.db.models import Count
from django.core.urlresolvers import reverse

# Create your models here.

class AnswerQuerySet(models.QuerySet):
    def add_rating(self):
        qs = self.annotate(rating2=Count('ratingUsers'))
        return qs

class Answer(models.Model):
    body = models.TextField(verbose_name=u'Текст ответа')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=u'Автор')
    rating = models.IntegerField(verbose_name=u'Рейтинг')
    ratingUsers = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                         blank=True,
                                         verbose_name=u'Лайкнувшие',
                                         related_name='likedAnswer')
    question = models.ForeignKey(questions.models.Question,
                                 related_name='answers',
                                 verbose_name=u'Вопрос')

    created_at = models.DateTimeField(auto_now_add=True,
                                      verbose_name=u'Время создания')

    updated_at = models.DateTimeField(auto_now=True,
                                      verbose_name=
                                          u'Время последнего изменения')

    def as_compact_dict(self, user):
        showLike = (user.is_authenticated()
                    and (not user in self.question.ratingUsers.all()))
        print(self.author, user, self.author == user)
        return {
                'pk' : self.pk,
                'body': self.body,
                'author': str(self.author),
                'edit': self.author == user,
                'editUrl': reverse('core:answers:edit', args=[self.pk]),
                'rating' : self.rating,
                'created_at': self.created_at.strftime('%H:%M %Y-%m-%d'),
                'showLike' : showLike,
                'user-avatar-url' : self.author.profile.avatar.url,
        }
    class Meta:
        verbose_name = u'Ответ'
        verbose_name_plural = u'Ответы'
        ordering = ['-rating']
    def __str__(self):
       return self.body[:100]

    objects = AnswerQuerySet.as_manager()

questions/models.py
# coding=utf-8

from django.db import models
from django.contrib.auth.models import User

from django.conf import settings
from django.db.models import Count
# Create your models here.

class QuestionQuerySet(models.QuerySet):
    def add_rating(self):
        qs = self.annotate(rating2=Count('ratingUsers'))
        print(qs)
        return qs

class Question(models.Model):
    title = models.CharField(max_length=255, verbose_name=u'Заголовок')
    body = models.TextField(verbose_name=u'Тект вопроса')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=u'Автор')
    rating = models.IntegerField(verbose_name=u'Рейтинг')
    ratingUsers = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                         blank=True,
                                         verbose_name=u'Лайкнувшие',
                                         related_name='liked')

    created_at = models.DateTimeField(auto_now_add=True,
                                      verbose_name=u'Время создания')

    updated_at = models.DateTimeField(auto_now=True,
                                      verbose_name=
                                          u'Время последнего изменения')
    def get_cent_answers_channel_name(self):
        return "questionChannel" + str(self.id)
    
    class Meta:
        verbose_name = u'Вопрос'
        verbose_name_plural = u'Вопросы'
        ordering = ['-rating']
    def __str__(self):
       return self.title[:50]

    objects = QuestionQuerySet.as_manager()

class Tag(models.Model):
    title = models.CharField(max_length=255, verbose_name=u'Название')

    questions = models.ManyToManyField(Question, blank=True,
                                       related_name='tags',
                                       verbose_name=u'Вопросы')

    class Meta:
        verbose_name = u'Тэг'
        verbose_name_plural = u'Тэги'

    def __str__(self):
       return self.title[:50]

questions/forms.py
# coding: utf-8
from django import forms

from django.forms import ModelForm, Textarea
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout
from crispy_forms.bootstrap import FormActions

from answers.models import Answer
from .models import Question, Tag

class QuestionsSortForm(forms.Form):
    SORT_CHOICES = (
        ('-rating', u'Рейтингу'),
        ('-updated_at', u'Дате последнего изменения'),
        ('-created_at', u'Дате создания'),
    )
    sort_field = forms.ChoiceField(choices = SORT_CHOICES,
                                   label = u'Сортировать по')
    filter_words = forms.CharField(label=u'Содержат')
    def __init__(self, *args, **kwargs):
        super(QuestionsSortForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.disable_csrf = True
        self.helper.form_class = 'form-inline'
        self.helper.field_template = 'bootstrap3/layout/inline_field.html'
        self.helper.form_method = 'POST'
        self.helper.add_input(Submit('submit', 'Изменить порядок'))

class AnswersSortForm(forms.Form):
    SORT_CHOICES = (
        ('-rating', u'Рейтингу'),
        ('-created_at', u'Дате создания'),
        ('-updated_at', u'Дате последнего изменения'),

    )
    sort_field = forms.ChoiceField(choices = SORT_CHOICES,
                                   label = u'Сортировать по')

    def __init__(self, *args, **kwargs):
        super(AnswersSortForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.disable_csrf = True
        self.helper.form_class = 'form-inline'
        self.helper.field_template = 'bootstrap3/layout/inline_field.html'
        self.helper.form_method = 'POST'
        self.helper.add_input(Submit('submit', 'Изменить порядок'))




class NewCommentForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super(NewCommentForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_method = 'POST'
        self.helper.add_input(Submit('submit', 'Отправить'))

    class Meta:
        model = Answer
        fields = ['body']

class NewQuestionForm(ModelForm):

    def __init__(self, *args, **kwargs):
        # Only in case we build the form from an instance
        # (otherwise, 'toppings' list should be empty)
        if kwargs.get('instance'):
            # We get the 'initial' keyword argument or initialize it
            # as a dict if it didn't exist.
            initial = kwargs.setdefault('initial', {})
            # The widget for a ModelMultipleChoiceField expects
            # a list of primary key for the selected data.
            initial['tags'] = [t.pk for t in kwargs['instance'].tags.all()]

        super(NewQuestionForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_method = 'POST'
        self.helper.add_input(Submit('submit', 'Задать вопрос'))

    tags = forms.ModelMultipleChoiceField(queryset=Tag.objects.all())

    def save(self, commit=True):
        # Get the unsave Pizza instance
        instance = forms.ModelForm.save(self, False)

        # Prepare a 'save_m2m' method for the form,
        old_save_m2m = self.save_m2m
        def save_m2m():
           old_save_m2m()
           # This is where we actually link the pizza with toppings
           instance.tags.clear()
           for topping in self.cleaned_data['tags']:
               instance.tags.add(topping)
        self.save_m2m = save_m2m

        # Do we need to save all changes now?
        if commit:
            instance.save()
            self.save_m2m()

        return instance

    class Meta:
        model = Question
        fields = ['title', 'body', 'tags']

answers/views.py
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from django.views.generic.edit import CreateView, UpdateView
from . import models
# Create your views here.

class AnswerEdit(UpdateView):
    model = models.Answer
    fields = ['body']

    def get_success_url(self):
        return reverse('core:questions:question', args=[self.question.pk])

    def dispatch(self, request, pk=None, *args, **kwargs):
        self.question = models.Answer.objects.get(pk=pk).question
        return super(AnswerEdit, self).dispatch(request, *args, **kwargs)

questions/views.py
from django.shortcuts import render, redirect, get_object_or_404
from . import models
from . import forms
import answers.models
import core.forms
from django.core.urlresolvers import reverse
from django.db.models import Count
# Create your views here.

from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView

def add_sort_method_to_self(self, request):
    sort_method_form = forms.QuestionsSortForm(request.GET)

    if (sort_method_form.is_valid()):
        self.sort_method = sort_method_form.data.get('sort_field')
        self.filter_words = sort_method_form.data.get('filter_words')
    else:
        self.sort_method = None
        self.filter_words = None

def sort_queryset(qs, method):
    if (method):
        qs = qs.order_by(method)
    return qs

class QuestionsList(ListView):
    model = models.Question
    template_name = "questions/all.html"

    def dispatch(self, request, *args, **kwargs):
        add_sort_method_to_self(self, request)
        return super(QuestionsList, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        queryset = sort_queryset(self.model.objects.all(), self.sort_method)
        if (self.filter_words):
            queryset = queryset.filter(title__icontains=self.filter_words)
        queryset = queryset.add_rating()
        return queryset

    def get_context_data(self, **kwargs):
        context = super(QuestionsList, self).get_context_data(**kwargs)

        context['sort_form'] = forms.QuestionsSortForm(initial=
            {
                'sort_field': self.sort_method,
                'filter_words': self.filter_words,
            }
        )
        return context


class QuestionDetail(CreateView):
    form_class = forms.NewCommentForm
    model = answers.models.Answer
    template_name = "questions/question.html"

    def get_success_url(self):
        answer = self.object
        from adjacent import Client
        client = Client()
        client.publish(answer.question.get_cent_answers_channel_name(),
                       answer.as_compact_dict(self.user))
        response = client.send()
        print(str(answer))
        print('sent to channel {}, got response from centrifugo: {}'
                .format(answer.question.get_cent_answers_channel_name(),
                        response))
        return self.request.path

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.question = self.question
        form.instance.rating = 0
        return super(QuestionDetail, self).form_valid(form)

    def dispatch(self, request, pk=None, *args, **kwargs):
        self.user = request.user
        self.question = get_object_or_404(models.Question, id=pk)
        sort_method_form = forms.AnswersSortForm(request.GET)

        if (sort_method_form.is_valid()):
            self.sort_method = sort_method_form.data.get('sort_field')
        else:
            self.sort_method = None

        print(self.question)
        return super(QuestionDetail, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(QuestionDetail, self).get_context_data(**kwargs)
        context['question'] = self.question
        context['answers'] = sort_queryset(self.question.answers.all(),
                                     self.sort_method)
        context['sort_form'] = forms.AnswersSortForm(initial=
            {'sort_field': self.sort_method}
        )
        context['ordering'] = self.sort_method
        return context

class QuestionAnswers(ListView):
    model = answers.models.Answer
    template_name = "questions/answers.html"

    def dispatch(self, request, pk=None, *args, **kwargs):
        self.question = get_object_or_404(models.Question, id=pk)
        sort_method_form = forms.AnswersSortForm(request.GET)

        if (sort_method_form.is_valid()):
            self.sort_method = sort_method_form.data.get('sort_field')
        else:
            self.sort_method = None

        print(self.question)
        return super(QuestionAnswers, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super(QuestionAnswers, self).get_queryset()
        return queryset

    def get_context_data(self, **kwargs):
        context = super(QuestionAnswers, self).get_context_data(**kwargs)

        context['question'] = self.question

        context['answers'] = sort_queryset(self.question.answers.all(),
                                     self.sort_method).add_rating()
        return context

class QuestionCreate(CreateView):
    model = models.Question
    template_name = 'questions/new.html'
    form_class = forms.NewQuestionForm

    def get_success_url(self):
        return reverse('core:questions:all')

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.rating = 0
        return super(QuestionCreate, self).form_valid(form)


class QuestionEdit(UpdateView):
    model = models.Question
    #fields = ['title', 'body']
    form_class = forms.NewQuestionForm

    def get_success_url(self):
        return reverse('core:questions:question', args=[self.pk])

    def dispatch(self, request, pk=None, *args, **kwargs):
        self.pk = pk
        return super(QuestionEdit, self).dispatch(request, *args, **kwargs)

questions/templates/questions/all.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{%block head %}
<link rel="stylesheet" type="text/css" href="/static/questions/questions.css" />
<script src="/static/questions/vote.js"> </script>
{%endblock%}

{% block jumbo %}
<div class="container">
 </div>
{% endblock %}


{%block content %}
<div class="text-center">
    <h1>Все вопросы</h1>
    <br>
</div>

<div class="clearfix">
    <div class="pull-right">

        <form action='{% url 'core:questions:all' %}' method="get" class="form-inline">
            <label> Сортировать по: </label>
            {% crispy sort_form %}
        </form>
    </div>
</div>

{% for question in object_list %}
    <hr>
    <div class="question">
        <div class="qRating" data-type="question" data-number="{{question.pk}}">
            <p>
                {{question.rating2}}
            </p>
            {% if user in question.ratingUsers.all %}

            {% else %}
                {% if user.is_authenticated %}
                    <button class="ratingUp btn btn-success" data-type="question" data-number="{{question.pk}}">
                        Like
                    </button>
                {% endif %}
            {% endif %}
        </div>

        <div class="qBody">
            <div class="qContainer">
                <div class="qTitle">
                    <a class="" href='{% url 'core:questions:question' question.pk %}'>
                        {{ question.title }}
                    </a>
                </div>

                <div class="qAuthor">
                    <div>
                        at {{question.created_at|date:'H:i d-m-Y'}}
                    </div>

                    <img src="{{question.author.profile.avatar.url}}" class="img-circle"  height="30px"/>

                    <span class="colored"> by {{question.author}} </span>

                </div>
                {% for tag in question.tags.all %}
                    <span class="tag"> {{tag.title}} </span>
                {%endfor%}

            </div>
        </div>
    </div>
{% endfor %}
<hr>

<div style="visibility:hidden" id="ajax" data-csrf="{{csrf_token}}" data-url="{% url 'core:ratingchange' %}">
</div>


{%endblock%}

questions/templates/questions/answers.html
{% if answers %}

    {% for answer in answers %}
    <hr>
        <div class="question">
            <div class="qRating" >
                <p>{{answer.rating2}}</p>
                {% if user in answer.ratingUsers.all %}

                {% else %}
                    {% if user.is_authenticated %}
                        <button class="ratingUp btn btn-success" data-type="answer" data-number="{{answer.pk}}">
                            Like
                        </button>
                    {%endif%}

                {% endif %}
            </div>

            <div class="qBody">

                <div class="qContainer">

                    <div class="qDesc text-center">
                        {{ answer.body }}
                    </div>
                    <div class="qAuthor">
                        <div>
                            {{answer.created_at|date:'H:i d-m-Y'}}
                        </div>
                        <span class="colored"> {{answer.author}} </span>
                        <img src="{{answer.author.profile.avatar.url}}" class="img-circle"  height="40px"/>
                    </div>
                </div>

                    {% if answer.author == user %}
                        <a href="{% url 'core:answers:edit' answer.pk %}">
                            Редактировать
                        </a>
                    {% endif %}

            </div>


        </div>
    {% endfor %}
{% else %}
    No answers yet
{% endif %}

questions/templates/questions/new.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{%block head %}
<link rel="stylesheet" type="text/css" href="/static/questions/questions.css" />
{%endblock%}

{%block content %}
<div class="curTitle">
    Новый вопрос
</div>

<form action="" method="post">
    {% csrf_token %}
    {% crispy form %}
</form>

{%endblock%}

questions/templates/questions/question.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{%block content %}

{%block head %}


<script src="//cdn.jsdelivr.net/sockjs/1.0/sockjs.min.js" type="text/javascript"></script>

<script src="/static/js/centrifuge.js"></script>

<script src="/static/questions/vote.js"> </script>
<script src="/static/questions/loadAnswers.js"></script>

<link rel="stylesheet" type="text/css" href="/static/questions/questions.css" />
<style>

</style>
{%endblock%}

<div class="question" style="border:solid; margin-top: 1em">
    <div class="qRating" data-type="question" data-number="{{question.pk}}">
        <p>{{ question.ratingUsers.count }}</p>
        {% if user in question.ratingUsers.all %}

        {% else %}
            {% if user.is_authenticated %}
                <button class="ratingUp btn btn-success" data-type="quesiton" data-number="{{question.pk}}">
                    Like
                </button>
            {%endif%}
        {% endif %}
    </div>
    <div class="qBody">
        <div class="qContainer">
            <div class="qTitle curTitle">
                <span>
                    {{ question.title }}
                </span>
            </div>
            <div class="qDesc">
                {{question.body}}
            </div>
            <div class="qAuthor">
                <div>
                    {{question.created_at|date:'H:i d-m-Y'}}
                </div>

                <img src="{{question.author.profile.avatar.url}}" class="img-circle"  height="40px"/>

                <span class="colored"> {{question.author}} </span>
            </div>
            {% for tag in question.tags.all %}
                <span class="tag"> {{tag.title}} </span>
            {%endfor%}
            <br>
        </div>
        <div>
            {% if question.author == user %}
                <a href="{% url 'core:questions:edit' question.pk %}">
                    Редактировать
                </a>
            {% endif %}
        </div>
    </div>

</div>

<div class="curTitle">
    Ответы
</div>



<div class="clearfix">
    <div class="pull-right">
        <form action='{% url 'core:questions:question' question.pk %}' method="get" class="form-inline">
            <label> Сортировать по: </label>
            {% crispy sort_form %}
        </form>
    </div>
</div>

<div id="answers">

</div>

<hr>

<div id="new_comment">
    {% if user.is_anonymous %}
        Чтобы ответить на вопрос,
        <a href="{% url 'core:login' %}?next={{request.path}}%23new_comment">
            войдите
        </a>
    {% else %}
    <form action="" method="post" >
        {% csrf_token %}
        {% crispy form %}
    </form>
    {% endif %}
</div>
<div style="visibility:hidden" id="ajax" data-csrf="{{csrf_token}}" data-url="{% url 'core:ratingchange' %}">
</div>
<div style="visibility:hidden" id="loader" data-url='{%url "core:questions:answers" pk=question.pk %}?sort_field={{ordering}}'>
</div>

<div id="answers-cent-data"
    data-cent-url="{{ CENTRIFUGE_SOCKJS_ENDPOINT }}"
    data-cent-user="{{ CENTRIFUGE_USER }}"
    data-cent-ts="{{ CENTRIFUGE_TIMESTAMP }}"
    data-cent-info="{{ CENTRIFUGE_INFO }}"
    data-cent-token="{{ CENTRIFUGE_TOKEN }}"
    data-cent-channel="{{ question.get_cent_answers_channel_name }}">

</div>
{%endblock%}

questions/templates/questions/question_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{%block head %}
<link rel="stylesheet" type="text/css" href="/static/questions/questions.css" />
{%endblock%}

{%block content %}
<div class="curTitle">
        Редактировать вопрос
</div>

<form action="" method="post">
    {% csrf_token %}
    {% crispy form %}
</form>

{%endblock%}