application/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls', namespace='core')),
]

core/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout
from . import views

urlpatterns = [
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, name='logout'),

    url(r'^questions/', include('questions.urls', namespace='questions')),
    url(r'^answers/', include('answers.urls', namespace='answers')),
    url(r'^ratingchange/', views.update_rating, name='ratingchange'),
    url(r'^$', views.index, name='index'),
]

core/models.py
# coding: utf-8

from django.db import models

# Create your models here.

core/forms.py
# coding: utf-8
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout
from crispy_forms.bootstrap import FormActions

class LoginForm(forms.Form):
    username = forms.CharField(label='', widget=forms.TextInput(
            attrs={'placeholder': 'username'}
        )
    )
    password = forms.CharField(label='', widget=forms.PasswordInput(
            attrs={'placeholder': 'password'}
        )
    )

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_class = 'form-inline'
        self.helper.field_template = 'bootstrap3/layout/inline_field.html'
        self.helper.add_input(Submit('submit', 'Log in'))
        #self.helper.add_input(Submit('submit', 'Изменить порядок'))

core/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
import answers.models
import questions.models
# Create your views here.

def update_rating(request):
    if (request.user.is_authenticated()):
        type = request.POST.get("type")
        id = request.POST.get("number")
        print(type, id)
        if (type == "answer"):
            try:
                answer = answers.models.Answer.objects.get(pk=int(id))
                if  not answer.ratingUsers.all().filter(pk=request.user.pk):
                    answer.ratingUsers.add(request.user)
                answer.rating = answer.ratingUsers.count();
                answer.save()
                return JsonResponse({'rating' : answer.ratingUsers.count()})
            except Exception as e:
                print(e)
        elif (type == "question"):
            try:
                question = questions.models.Question.objects.get(pk=int(id))
                if not question.ratingUsers.all().filter(pk=request.user.pk):
                    question.ratingUsers.add(request.user)
                question.rating = question.ratingUsers.count();
                question.save()
                return JsonResponse({'rating' : question.ratingUsers.count()})
            except Exception as e:
                print(e)


def index(request):
    return redirect('core:questions:all')

core/templates/base.html
{% load crispy_forms_tags %}
<html>
    <head>
        <script   src="https://code.jquery.com/jquery-2.2.3.min.js"   integrity="sha256-a23g1Nt4dtEYOj7bR+vTu7+T8VP13humZFBJNIYoEJo="   crossorigin="anonymous"></script>
        <title> Best Q&amp;A site ever! </title>
        <link href='http://fonts.googleapis.com/css?family=Muli' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type="text/css" href="/static/base.css" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous" />
        <!-- CSS -->
        <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/chosen/1.1.0/chosen.min.css">

        <!-- JS -->
        <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/chosen/1.1.0/chosen.jquery.min.js"></script>
        <script type="text/javascript" src='/static/questions/select.js'></script>
        {%block head%}

        {%endblock%}
    </head>
    <body>
        {% include "navbar.html" %}
        <div class="jumbotron">
            {% block jumbo %}
            {% endblock %}
        </div>
        <div class="row marketing">
            <div class="col-md-1">
            </div>
            <div class="col-md-10">
                {%block content%}
                {%endblock%}
            </div>
            <div class="col-md-1">
            </div>
        </div>
    </body>
</html>

core/templates/navbar.html
{% load crispy_forms_tags %}
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="/">[STACKOVERFLOW]</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="{% url 'core:questions:create' %}">Задать вопрос</a></li>
            </ul>
            {% if user.is_anonymous %}
                <form class="navbar-form navbar-right" method="post" action="{% url 'core:login' %}?next={% if next %}{{next}}{% else %}{{request.path}}{% endif %}">
                    {%csrf_token%}
                    {% crispy login_form %}
                    <input type="hidden" name="next" value="{% if next %}{{next}}{% else %}{{request.path}}{% endif %}" />1
                </form>
            {% else %}
                <form  class="navbar-form navbar-right" method="post" action="{% url 'core:logout' %}?next={% if next %}{{next}}{% else %}{{request.path}}{% endif %}">
                    <span class="whiteText"> Hello, {{ user }} </span>
                    {% csrf_token %}
                    <input type="submit" class="btn btn-success"  value="Log out" />
                </form>
            {% endif %}
        </div>
    <!--/.nav-collapse -->
    </div>
</nav>